### ISSUE TITLE
32 bit builds are not working

### ISSUE THREAD

**Issue by Dadoum** [andrewlalis/handy-httpd#5]
**Describe the bug**
Trying to build handy-httpd for a 32 bit machine does not work anymore.

It worked in 3.3.0, but not in 5.1.0 nor 5.2.0.

**Versions**
Fedora 37 x86_64, with gdc 12.2 cross-compiler to arm.

**Steps to Reproduce**
Install a cross compiler and use it to build the library.

Here is the output:

```
[dadoum@fedora bin]$ dub build handy-httpd@5.2.0 --compiler arm-linux-gnueabihf-gdc 
    Fetching handy-httpd 5.2.0
             Building package handy-httpd in /home/dadoum/.dub/packages/handy-httpd-5.2.0/handy-httpd/
    Starting Performing "debug" build using arm-linux-gnueabihf-gdc for arm, arm_hardfloat.
    Building handy-httpd 5.2.0: building configuration [library]
SSE: false
../../../.dub/packages/handy-httpd-5.2.0/handy-httpd/source/handy_httpd/components/response.d:120:26: error: cannot implicitly convert expression 'cast(ulong)data.length > bytesToWrite ? bytesToWrite : cast(ulong)data.length' of type 'ulong' to 'uint'
  120 |             size_t idx = data.length > bytesToWrite ? bytesToWrite : data.length;
      |                          ^
../../../.dub/packages/handy-httpd-5.2.0/handy-httpd/source/handy_httpd/components/response.d:136:28: error: template instance 'handy_httpd.components.response.HttpResponse.writeBodyRange!(ubyte[][])' error instantiating
  136 |         this.writeBodyRange([data], data.length, contentType);
      |                            ^
../../../.dub/packages/handy-httpd-5.2.0/handy-httpd/source/handy_httpd/components/response.d:120:26: error: cannot implicitly convert expression 'cast(ulong)data.length > bytesToWrite ? bytesToWrite : cast(ulong)data.length' of type 'ulong' to 'uint'
  120 |             size_t idx = data.length > bytesToWrite ? bytesToWrite : data.length;
      |                          ^
../../../.dub/packages/handy-httpd-5.2.0/handy-httpd/source/handy_httpd/components/responses.d:54:32: error: template instance 'handy_httpd.components.response.HttpResponse.writeBodyRange!(ByChunkImpl)' error instantiating
   54 |         response.writeBodyRange(file.byChunk(8192), size, type);
      |                                ^
Error arm-linux-gnueabihf-gdc failed with exit code 1.
```

**Comment by andrewlalis** [comment]
Yeah, this looks like something that's fixable; I'm not available today though; but I'll look at it when I have time next week.

**Comment by andrewlalis** [comment]
Alright, I've made some changes to how the `response.readBody` method is done to hopefully make it compatible. See if you can compile 5.2.1.

**Comment by Dadoum** [comment]
It is now compiling correctly. Thanks for the quick fix.
